pipeline {
    agent {
        node {
            label 'Agent-node'
        }
    }
     environment {
        def appVersion = ""
     }
    stages {
        stage('Read Package Info') {
            steps {
                script {
                    dir('piplines/catalogue') {
                        def packageJson = readJSON file: 'package.json'
                        appVersion = packageJson.version
                        echo "The application version is: ${appVersion}"
                    }
                }
            }
        }
        stage('Another Stage') {
            steps {
                echo "Using version: ${appVersion}"
            }
        }
    }
}