pipeline {

    agent {
        node {
            label 'Agent-node'
        }
    }

    stages {
        stage('Read Package Info') {
            steps {
                script {
                    // Read and parse the JSON file
                    def packageJson = readJSON file: 'package.json'
                    
                    // Extract fields into variables
                    def appName = packageJson.name
                    def appVersion = packageJson.version
                    
                    // Print values
                    echo "Building ${appName} - Version: ${appVersion}"
                    
                    // Optional: Use a version for the Jenkins build display name
                    currentBuild.displayName = "#${BUILD_NUMBER}-${appVersion}"
                }
            }
        }
    }
}